#!/bin/sh

CMD=$1
NODENAME="`date +advsystem_ctl_%H_%M_%S_%N`@localhost"
NODEMAIN="advsystem@localhost"
COOKIE=OCFDAZSCILRVUEHEWFWA

ERL_ARGS="+K true +A 128 +P 1000000"

LOCALLBINPATH=`find ./ebin -type d -printf '%h/%f '`
OTHERBINPATH="./deps/*/ebin"
BINPATH=${LOCALLBINPATH}${OTHERBINPATH}

if [ "$CMD" != "start" ]; then
  erl \
    -noinput \
    -pz $LOCALLBINPATH \
    -sname ${NODENAME} \
    -s ctl \
    -hidden \
    -connect_all false \
    ${ERL_ARGS} \
    -extra -n ${NODEMAIN} \
    "$@"
else
  shift
  ./start.sh $@
fi
